---
name: SVN-Friendly
version: 0.999_001
author:
  - Elizabeth Grace Frank-Backman
abstract: user friendly front end to Subversion bindings
license: perl
requires:
  Exception::Lite: 0
  SVN::Client: 0
  SVN::Repos: 0
  SVN::Wc: 0
  perl: '>= 5.8.8'
provides:
  DB:
    file: lib/Exception/Lite.pm
  Exception::Lite:
    file: lib/Exception/Lite.pm
  SVN::Core:
    file: lib/SVN/Friendly/Config.pm
  SVN::Depth:
    file: lib/SVN/Friendly/Client.pm
  SVN::Friendly::Client:
    file: lib/SVN/Friendly/Client.pm
  SVN::Friendly::Config:
    file: lib/SVN/Friendly/Config.pm
  SVN::Friendly::Dates:
    file: lib/SVN/Friendly/Dates.pm
  SVN::Friendly::Exceptions:
    file: lib/SVN/Friendly/Exceptions.pm
  SVN::Friendly::List::Fields:
    file: lib/SVN/Friendly/Client.pm
  SVN::Friendly::Repos:
    file: lib/SVN/Friendly/Repos.pm
  SVN::Friendly::Utils:
    file: lib/SVN/Friendly/Utils.pm
  SVN::Wc::Notify::Action:
    file: lib/SVN/Friendly/Client.pm
  SVN::_Core:
    file: lib/SVN/Friendly/Client.pm
generated_by: Module::Build version 0.26
